config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :gamerooms do
    resource :gameroom_users


  end
  devise_for :users
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/gameroom.rb
class Gameroom < ApplicationRecord
  has_many :gameroom_users
  has_many :users , through: :gameroom_users
  belongs_to :user, optional: true
end

app/models/gameroom_user.rb
class GameroomUser < ApplicationRecord
  belongs_to :gameroom
  belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :game_room, optional:true
  has_many :gameroom_users
  has_many :gamerooms, through: :gameroom_users
  has_many :gamerooms
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gameroom_users_controller.rb
class GameroomUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_gameroom
  def create
    @gameroom_user = @gameroom.gameroom_users.where(user_id: current_user.id).first_or_create
    redirect_to @gameroom
  end

  def destroy
    @gameroom_user = @gameroom.gameroom_users.where(user_id: current_user.id).destroy_all
    redirect_to gamerooms_path
  end

  private

    def set_gameroom
      @gameroom = Gameroom.find(params[:gameroom_id])
    end
end

app/controllers/gamerooms_controller.rb
class GameroomsController < ApplicationController

  # GET /gamerooms
  # GET /gamerooms.json
  def index
    @gamerooms = Gameroom.all
  end

  # GET /gamerooms/1
  # GET /gamerooms/1.json
  def show
  end

  # GET /gamerooms/new
  def new
    @gameroom = Gameroom.new
  end

  # GET /gamerooms/1/edit
  def edit
  end

  # POST /gamerooms
  # POST /gamerooms.json
  def create
    @gameroom = Gameroom.new

    if @gameroom.save
      redirect_to @gameroom
    else
      render 'new'
    end
  end

  # PATCH/PUT /gamerooms/1
  # PATCH/PUT /gamerooms/1.json
  def update
    respond_to do |format|
      if @gameroom.update(gameroom_params)
        format.html { redirect_to @gameroom, notice: 'Gameroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @gameroom }
      else
        format.html { render :edit }
        format.json { render json: @gameroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamerooms/1
  # DELETE /gamerooms/1.json
  def destroy
    @gameroom.destroy
    respond_to do |format|
      format.html { redirect_to gamerooms_url, notice: 'Gameroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def gameroom_params
      params.require(:gameroom).permit(:name)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
    @game_room = GameRoom.first
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.fetch(:game, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.fetch(:page, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gamerooms_helper.rb
module GameroomsHelper
  def hello
    ActionCable.server.broadcast 'web_notifications_1', { title: 'New things!', body: "All that's fit for print" }

  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/gamerooms/_form.html.erb
<%= form_with(model: gameroom, local: true) do |f| %>
  <% if gameroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gameroom.errors.count, "error") %> prohibited this gameroom from being saved:</h2>

      <ul>
      <% gameroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gamerooms/edit.html.erb
<h1>Editing Gameroom</h1>

<%= render 'form', gameroom: @gameroom %>

<%= link_to 'Show', @gameroom %> |
<%= link_to 'Back', gamerooms_path %>

app/views/gamerooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gamerooms</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <h1>Joined Gamerooms</h1>

<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>


  <% current_user.gamerooms.each do |gameroom| %>
    <%= link_to gameroom.name , gameroom%>
  <% end %>

  <tbody>
    <% @gamerooms.each do |gameroom| %>
      <tr>
        <td><%= link_to 'Show', gameroom %></td>
        <td><%= link_to 'Edit', edit_gameroom_path(gameroom) %></td>
        <td><%= link_to 'Destroy', gameroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Join', gameroom_gameroom_users_path(gameroom), method: :post %></td>
        <td><%= link_to 'Leave', gameroom_gameroom_users_path(gameroom), method: :delete %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gameroom', new_gameroom_path %>

app/views/gamerooms/new.html.erb
<h1>New Gameroom</h1>

<%= render 'form', gameroom: @gameroom %>

<%= link_to 'Back', gamerooms_path %>

app/views/gamerooms/show.html.erb
  <style>
    #world {
      position: absolute;
      width: 100%;
      height: 100%;
      top:0;
      left:0;
      overflow: hidden;
      background:#35404F;
      transition: background 400ms ease-in-out;
    }

    .overlay{
      position: absolute;
      top:0;
      left:0;
      width:100%;
      height:100%;
      background:rgba(0,0,0,0);
      position: none;
    }

    .name{
      color:white;
      font-size:20px;
    }

      .f{
        color:white;
        float:left;
      }
      .s{
        color:white;

        float:right;
      }


  </style>


<div id="world"></div>
<div class = "overlay">
  <p id="notice"><%= notice %></p>

  <p class = "f"><%= @gameroom.users.first.email %></p>
  <p class = "s"><%= @gameroom.users.second.email %></p>

</div>

<script>

    $(window).on("load",()=>{init();});

    let Colors = {
        red:0xf25346,
        white:0xd8d0d1,
        brown:0x59332e,
        pink:0xF5986E,
        neon:0xFF ,
        brownDark:0x23190f,
        blue:0x68c3c0,
    };
    let init = ()=> {
        createScene();
        createLights();
        createPlane();
        createSea();
        createSky();
        document.addEventListener('mousemove',handleMouseMove, false);
        loop();
    };

    var mousePos = {x:0,y:0};

    function handleMouseMove(event){
        var tx = -1 + (event.clientX / WIDTH)*2;
        var ty = 1 - (event.clientY / HEIGHT)*2;
        mousePos = {x:tx,y:ty};
    }

    let scene, camera, fieldOfView, aspectRatio, nearPlane, farPlane, HEIGHT, WIDTH,
        renderer,container,hemisphereLight, shadowLight;;

    let createScene = () => {
        HEIGHT = window.innerHeight;
        WIDTH = window.innerWidth;
        scene = new THREE.Scene();

        scene.fog = new THREE.Fog(Colors.blue, 100, 950);

        aspectRatio = WIDTH / HEIGHT;
        fieldOfView = 60;
        nearPlane = 1;
        farPlane = 10000;

        camera = new THREE.PerspectiveCamera(
            fieldOfView,aspectRatio,nearPlane,farPlane
        );

        camera.position.x = 0;
        camera.position.z = 200;
        camera.position.y = 100;

        renderer = new THREE.WebGLRenderer({
            alpha: true,
            antialias: true
        });

        renderer.setSize(WIDTH,HEIGHT);

        renderer.shadowMap.enabled = true;

        container = document.getElementById("world");

        container.appendChild(renderer.domElement);

        window.addEventListener('resize',handleWindowResize,false);
    };

    function handleWindowResize(){
        HEIGHT = window.innerHeight;
        WIDTH = window.innerWidth;
        renderer.setSize(WIDTH,HEIGHT);
        camera.aspect= WIDTH/HEIGHT;
        camera.updateProjectionMatrix()

    }

    let createLights = () => {
        hemisphereLight = new THREE.HemisphereLight(0xaaaaaa,0x000000, .9);
        shadowLight = new THREE.DirectionalLight(0xffffff, .9);
        shadowLight.position.set(150,350,350);
        shadowLight.castShadow = true;
        shadowLight.shadow.camera.left = -400;
        shadowLight.shadow.camera.right = 400;
        shadowLight.shadow.camera.top = 400;
        shadowLight.shadow.camera.bottom = -400;
        shadowLight.shadow.camera.near = 1;
        shadowLight.shadow.camera.far = 10000;
        shadowLight.shadow.mapSize.width = 2048;
        shadowLight.shadow.mapSize.height = 2048;

        scene.add(hemisphereLight);
        scene.add(shadowLight);
    };

    Sea = function() {
        var geom = new THREE.CylinderGeometry(600,600,800,40,10);
        geom.applyMatrix(new THREE.Matrix4().makeRotationX(-Math.PI/2));

        var mat = new THREE.MeshPhongMaterial({
            color:Colors.blue,
            transparent: true,
            opacity: .6,
            shading: THREE.FlatShading,
        });

        this.mesh = new THREE.Mesh(geom, mat);
        this.mesh.receiveShadow = true;
    };

    var sea;

    function createSea(){
        sea = new Sea();
        sea.mesh.position.y = -600;
        scene.add(sea.mesh);
    }

    Cloud = function () {
        this.mesh = new THREE.Object3D();
        var geom = new THREE.BoxGeometry(Math.floor(Math.random() * (100 - 50)) + 50,.6,.6);
        var mat = new THREE.MeshPhongMaterial({
            color:Colors.neon
        });
        var nBlocs = 30+Math.floor(Math.random()*30);
        for(var i=0;i<nBlocs;i++){
            var m = new THREE.Mesh(geom,mat);
            m.position.x = i*55;
            m.position.y = Math.random()*20;
            m.position.z = Math.random()*100;
            m.rotation.z = Math.random()*Math.PI*100;
            m.rotation.y = Math.random()*Math.PI*20;

            var s = .1 + Math.random()*.9;
            m.scale.set(s,s,s);
            m.castShadow = true;
            m.receiveShadow = true;
            this.mesh.add(m);
        }
    };

    Sky = function(){
        this.mesh = new THREE.Object3D();

        this.nClouds = 20;
        var stepAngle = Math.PI*2/this.nClouds;

        for(var i =0;i<this.nClouds;i++){
            var c = new Cloud();
            var a = stepAngle*i;
            var h = 750+Math.random()*200;
            c.mesh.position.y = Math.sin(a)*h;
            c.mesh.position.x = Math.cos(a)*h;
            c.mesh.rotation.z = a + Math.PI/2;
            c.mesh.position.z = -400-Math.random()*400;
            var s = 1+Math.random()*2;
            c.mesh.scale.set(s,s,s);
            this.mesh.add(c.mesh);
        }
    };

    var sky;

    function createSky(){
        sky = new Sky();
        sky.mesh.position.y = -600;
        scene.add(sky.mesh);
    }


    var AirPlane = function() {

        this.mesh = new THREE.Object3D();

        // Create the cabin
        var geomCockpit = new THREE.BoxGeometry(60,50,50,1,1,1);
        var matCockpit = new THREE.MeshPhongMaterial({color:Colors.red, shading:THREE.FlatShading});
        var cockpit = new THREE.Mesh(geomCockpit, matCockpit);
        cockpit.castShadow = true;
        cockpit.receiveShadow = true;
        this.mesh.add(cockpit);

        // Create the engine
        var geomEngine = new THREE.BoxGeometry(20,50,50,1,1,1);
        var matEngine = new THREE.MeshPhongMaterial({color:Colors.white, shading:THREE.FlatShading});
        var engine = new THREE.Mesh(geomEngine, matEngine);
        engine.position.x = 40;
        engine.castShadow = true;
        engine.receiveShadow = true;
        this.mesh.add(engine);

        // Create the tail
        var geomTailPlane = new THREE.BoxGeometry(15,20,5,1,1,1);
        var matTailPlane = new THREE.MeshPhongMaterial({color:Colors.red, shading:THREE.FlatShading});
        var tailPlane = new THREE.Mesh(geomTailPlane, matTailPlane);
        tailPlane.position.set(-35,25,0);
        tailPlane.castShadow = true;
        tailPlane.receiveShadow = true;
        this.mesh.add(tailPlane);

        // Create the wing
        var geomSideWing = new THREE.BoxGeometry(40,8,150,1,1,1);
        var matSideWing = new THREE.MeshPhongMaterial({color:Colors.red, shading:THREE.FlatShading});
        var sideWing = new THREE.Mesh(geomSideWing, matSideWing);
        sideWing.castShadow = true;
        sideWing.receiveShadow = true;
        this.mesh.add(sideWing);

        // propeller
        var geomPropeller = new THREE.BoxGeometry(20,10,10,1,1,1);
        var matPropeller = new THREE.MeshPhongMaterial({color:Colors.brown, shading:THREE.FlatShading});
        this.propeller = new THREE.Mesh(geomPropeller, matPropeller);
        this.propeller.castShadow = true;
        this.propeller.receiveShadow = true;

        // blades
        var geomBlade = new THREE.BoxGeometry(1,100,20,1,1,1);
        var matBlade = new THREE.MeshPhongMaterial({color:Colors.brownDark, shading:THREE.FlatShading});

        var blade = new THREE.Mesh(geomBlade, matBlade);
        blade.position.set(8,0,0);
        blade.castShadow = true;
        blade.receiveShadow = true;
        this.propeller.add(blade);
        this.propeller.position.set(50,0,0);
        this.mesh.add(this.propeller);
    };




    var airplane;

    function createPlane(){
        airplane = new AirPlane();
        airplane.mesh.scale.set(.25,.25,.25);
        airplane.mesh.position.y= 100;
        scene.add(airplane.mesh);


        airplane2 = new AirPlane();
        airplane2.mesh.scale.set(.25,.25,.25);
        airplane2.mesh.position.y = 100;
        airplane2.mesh.rotateY(160);
        scene.add(airplane2.mesh);


    }

    function updatePlane(){
        var targetX = normalize(mousePos.x, -1, 1, -200, 100);
        var targetY = normalize(mousePos.y, -1, 1, 25, 175);

        var targetX2 = normalize(mousePos.x, -1, 1, -200, 200);
        var targetY2 = normalize(mousePos.y, -1, 1, 25, 175);

        <% if @gameroom.users.first.email == current_user.email %>
          airplane.mesh.position.y = targetY;
          airplane.mesh.position.x = targetX;
        <% end %>

        <% if @gameroom.users.second.email == current_user.email %>
          airplane2.mesh.position.y = targetY2;
          airplane2.mesh.position.x = targetX2;
        <% end %>


        airplane.propeller.rotation.x += 0.3;

        airplane2.propeller.rotation.x += 0.3;

    }



    function normalize(v,vmin,vmax,tmin,tmax){
        var nv = Math.max(Math.min(v,vmax), vmin);
        var dv = vmax-vmin;
        var pc = (nv-vmin)/dv;
        var dt = tmax-tmin;
        var tv = tmin+(pc*dt);
        return tv;
    }



    function loop(){

        sea.mesh.rotation.z += .005;
        sky.mesh.rotation.z += .01;
        updatePlane();
        $(window).keypress(()=>{
            moveBullet();


        });
        renderer.render(scene,camera);
        requestAnimationFrame(loop);
    }

</script>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MultiplayerGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'three.min' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>